development:
  adapter: postgresql
  encoding: unicode
  database: system_development
  pool: 5
  username: yunxuan
  password: 19900818

test: &test
  adapter: postgresql
  encoding: unicode
  database: system_test
  pool: 5
  username: yunxuan
  password: 19900818

production:
  adapter: postgresql
  encoding: unicode
  database: system_production
  pool: 5
  username: yunxuan
  password: 19900818

cucumber:
  <<: *test

